module: SwiftKueryPostgreSQL
author: IBM
github_url: https://github.com/Kitura-Next/Swift-Kuery-PostgreSQL/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftKueryPostgreSQL.xcodeproj, -target, SwiftKueryPostgreSQL, LIBRARY_SEARCH_PATHS=.build/debug]
